"""added stream number

Revision ID: 8483419f3504
Revises: 5b33f6ac7afe
Create Date: 2025-04-20 23:48:24.675780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8483419f3504'
down_revision: Union[str, None] = '5b33f6ac7afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('number_of_stream', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'number_of_stream')
    # ### end Alembic commands ###
