"""added deneme_k

Revision ID: caaf10c04f71
Revises: 6baf94a1afe2
Create Date: 2025-04-21 22:32:12.164899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaf10c04f71'
down_revision: Union[str, None] = '6baf94a1afe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('deneme_k', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'deneme_k')
    # ### end Alembic commands ###
