name: Build and deploy container app to Azure Web App - album-fastapi-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://albumfastapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1464edf59507416c9d11610e5d246f4c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d7a9061318fc4d0a9618e70dde9fd3ed }}

    - name: Build and push container image to registry with :latest tag
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          albumfastapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1464edf59507416c9d11610e5d246f4c }}/myfastapiapp:latest
          albumfastapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1464edf59507416c9d11610e5d246f4c }}/myfastapiapp:${{ github.sha }}
        file: ./Dockerfile

    - name: Run Alembic migrations
      run: |
        docker run --rm albumfastapi.azurecr.io/myfastapiapp:${{ github.sha }} alembic upgrade head

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy :latest image to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'album-fastapi-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2f0de78cc051482b8c6dfaa1cb7b68cf }}
        images: 'albumfastapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1464edf59507416c9d11610e5d246f4c }}/myfastapiapp:latest'